### ISSUE TITLE
Search is not working for Chains

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#13]
1. We created a new chain with ID: 3738946338482897
2. We added some rests underneath. For example, this rest: 6610813061096728
3. We created in that rest a new delvery Area (just for the sake of changing something and saving)
4. The following `search` call doesn't work:
```
{
    "type":"search",
    "filter":{"chainId":"3738946338482897"},
    "states":["operational"],
    "query":null,
    "chargeTypes":null,
    "fields":["media","orders","features","creditcardsInfo","id","openTimes","deliveryTypes","picture","timezone","maxFutureOrdersDelayMins","address","title","locale","deliveryInfos","currency"],
    "limit":null,
    "excludeIds":null,
    "radius":null
}
```
The exact same search works with other old chain ids

**Comment by dleshem** [comment]
This request returns 6610813061096728 now. Are there any other restaurant IDs you expect to see there?

**Comment by tomerb15** [comment]
Thanks for the help, is there anything we could have done on our own for next time?

**Comment by dleshem** [comment]
No. We're working on a new search API ("v2") that should resolve these issues.

**Comment by tomerb15** [comment]
This restaurant is still missing from the results:
5952539696633519

We get 4 restaurants now.

**Comment by dleshem** [comment]
Should be fine now - please confirm and close issue.

**Comment by tomerb15** [comment]
Nope, still only 4 returned. Have you seen it working? if so i'll recheck my code
